In [65]:
# Import the required libraries:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [66]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [67]:
# Read the CSV file:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AI/student-mat.csv", sep=';')
data

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]

In [68]:
data['sex'] = data['sex'].replace({'M':0, 'F':1})
data

school  sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP    1   18       U     GT3       A     4     4   at_home   teacher   
1       GP    1   17       U     GT3       T     1     1   at_home     other   
2       GP    1   15       U     LE3       T     1     1   at_home     other   
3       GP    1   15       U     GT3       T     4     2    health  services   
4       GP    1   16       U     GT3       T     3     3     other     other   
..     ...  ...  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS    0   20       U     LE3       A     2     2  services  services   
391     MS    0   17       U     LE3       T     3     1  services  services   
392     MS    0   21       R     GT3       T     1     1     other     other   
393     MS    0   18       R     LE3       T     3     2  services     other   
394     MS    0   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]

In [69]:
# Consider features we want to work on:
X = data.drop(['G3','school','Pstatus','address','famsize', 'Mjob', 'Fjob','reason', 'guardian' ], axis = 'columns').replace({'no':0, 'yes':1}).to_numpy()
X

array([[ 1, 18,  4, ...,  6,  5,  6],
       [ 1, 17,  1, ...,  4,  5,  5],
       [ 1, 15,  1, ..., 10,  7,  8],
       ...,
       [ 0, 21,  1, ...,  3, 10,  8],
       [ 0, 18,  3, ...,  0, 11, 12],
       [ 0, 19,  1, ...,  5,  8,  9]])

In [70]:
Y = data['G3'].to_numpy()
Y

array([ 6,  6, 10, 15, 10, 15, 11,  6, 19, 15,  9, 12, 14, 11, 16, 14, 14,
       10,  5, 10, 15, 15, 16, 12,  8,  8, 11, 15, 11, 11, 12, 17, 16, 12,
       15,  6, 18, 15, 11, 13, 11, 12, 18, 11,  9,  6, 11, 20, 14,  7, 13,
       13, 10, 11, 13, 10, 15, 15,  9, 16, 11, 11,  9,  9, 10, 15, 12,  6,
        8, 16, 15, 10,  5, 14, 11, 10, 10, 11, 10,  5, 12, 11,  6, 15, 10,
        8,  6, 14, 10,  7,  8, 18,  6, 10, 14, 10, 15, 10, 14,  8,  5, 17,
       14,  6, 18, 11,  8, 18, 13, 16, 19, 10, 13, 19,  9, 16, 14, 13,  8,
       13, 15, 15, 13, 13,  8, 12, 11,  9,  0, 18,  0,  0, 12, 11,  0,  0,
        0,  0, 12, 15,  0,  9, 11, 13,  0, 11,  0, 11,  0, 10,  0, 14, 10,
        0, 12,  8, 13, 10, 15, 12,  0,  7,  0, 10,  7, 12, 10, 16,  0, 14,
        0, 16, 10,  0,  9,  9, 11,  6,  9, 11,  8, 12, 17,  8, 12, 11, 11,
       15,  9, 10, 13,  9,  8, 10, 14, 15, 16, 10, 18, 10, 16, 10, 10,  6,
       11,  9,  7, 13, 10,  7,  8, 13, 14,  8, 10, 15,  4,  8,  8, 10,  6,
        0, 17, 13, 14,  7

In [71]:
from sklearn.model_selection import train_test_split # suddivide le osservazioni nei due insiemi

X_train, X_test, y_train, y_test = train_test_split(X, Y,
                                                    test_size = 0.33,
                                                    random_state = 123) # fix random seed for replicability

In [72]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((264, 24), (264,), (131, 24), (131,))

In [73]:
print(X_train[:10])
print(f'y_train = {y_train[:10]}')

[[ 0 15  2  2  1  4  0  0  1  0  1  1  1  1  0  4  3  4  1  1  4  6 11 13]
 [ 0 17  3  3  1  2  0  0  0  0  1  0  1  1  0  4  3  4  1  4  4  4  6  5]
 [ 0 18  2  1  2  1  0  0  0  0  1  0  1  1  1  4  4  3  1  3  5  5  7  6]
 [ 1 15  2  3  2  1  0  0  1  0  1  1  1  0  0  3  5  1  1  1  5  0  8  7]
 [ 0 18  2  2  1  1  2  0  1  0  1  1  1  1  0  3  3  3  1  2  4  0  7  4]
 [ 1 16  3  3  1  2  0  1  1  1  1  1  1  1  0  4  3  3  2  4  5 54 11 12]
 [ 1 15  4  4  1  1  0  1  1  1  0  1  1  1  0  3  3  4  2  3  5  0  8 10]
 [ 0 16  4  2  1  2  0  0  0  0  1  1  1  1  0  4  5  1  1  3  5  2 15 15]
 [ 1 17  2  2  1  2  0  0  1  0  0  1  1  0  1  4  2  2  1  1  3 12 11  9]
 [ 1 18  1  1  2  4  0  0  1  1  1  1  1  0  0  5  2  2  1  1  3  1 12 12]]
y_train = [14  6  7  6  0 11 11 16  9 12]


In [74]:
poly = PolynomialFeatures(degree = 3)
X_train_poly = poly.fit_transform(X_train)

In [75]:
modello = LinearRegression()
modello.fit(X_train_poly, y_train)

LinearRegression()

In [76]:
X_test_poly = poly.transform(X_test)
predict = modello.predict(X_test_poly)

In [77]:
print(f'dati predetti dal metodo = {predict[:10].round(decimals=2)}') # dati predetti dal metodo
print(f'dati reali presenti nel dataset di test = {y_test[:10]}') # dati effettivi presenti nel test set

dati predetti dal metodo = [10.73 18.48 10.28 -2.49 13.91  8.62  3.28  8.84 16.55 12.73]
dati reali presenti nel dataset di test = [ 8 13 12  0 10 12  5  0 16 13]


In [78]:
from sklearn.metrics import r2_score, mean_squared_error

# The coefficients
print('Coefficients: \n', modello.coef_)

# The mean squared error
print('Mean squared error: %.2f' %mean_squared_error(y_test, predict))

# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f' %r2_score(y_test, predict))

Coefficients: 
 [ 6.28421901e-07 -4.86741386e-04 -2.66463439e-04 ...  1.34839622e-03
 -1.41012360e-02  1.79168904e-03]
Mean squared error: 13.61
Coefficient of determination: 0.37
