In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
hardware = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AI/machine.data',   header=None)
hardware

0              1    2     3      4    5   6    7    8    9
0    adviser          32/60  125   256   6000  256  16  128  198  199
1     amdahl         470v/7   29  8000  32000   32   8   32  269  253
2     amdahl        470v/7a   29  8000  32000   32   8   32  220  253
3     amdahl        470v/7b   29  8000  32000   32   8   32  172  253
4     amdahl        470v/7c   29  8000  16000   32   8   16  132  132
..       ...            ...  ...   ...    ...  ...  ..  ...  ...  ...
204   sperry           80/8  124  1000   8000    0   1    8   42   37
205   sperry  90/80-model-3   98  1000   8000   32   2    8   46   50
206   sratus             32  125  2000   8000    0   2   14   52   41
207     wang         vs-100  480   512   8000   32   0    0   67   47
208     wang          vs-90  480  1000   4000    0   0    0   45   25

[209 rows x 10 columns]

In [ ]:
bank =  pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AI/bank-full.csv', sep=';')
bank

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

1. una breve descrizione in italiano del problema che si sta trattando e della classe di appartenenza (classificazione o regressione)



In [ ]:
#1
'''
Il dataset della banca contiene i dati relativi ai clienti contattati per campagne marketing. Il target indica se il cliente ha sottoscritto un deposito a termine, quindi si tratta di una classificazione

Il dataset riguardante l'hardaware contiene i dati relativi alle performance di una serie di calcolatori. Il target indica le loro prestazioni, quindi serve la regressione.
'''

" \nIl dataset della banca contiene i dati relativi ai clienti contattati per campagne marketing. Il target indica se il cliente ha sottoscritto un deposito a termine, quindi si tratta di una classificazione\n\nIl dataset riguardante l'hardaware contiene i dati relativi alle performance di una serie di calcolatori. Il target indica le loro prestazioni, quindi serve la regressione.\n"

2. la lista delle variabili dipendenti e di quelle indipendenti. Indicare se tutte le variabili indipendenti sono necessarie e, nel caso, eliminare quelle non necessarie
3. il controllo se sono presenti dati nulli e, nel caso, le istruzioni per eliminarli

In [ ]:
import numpy as np

In [ ]:
xH = hardware.drop([0, 1,9], axis = 'columns').to_numpy()
yH = hardware[9].to_numpy()
print(xH, yH)

[[  125   256  6000 ...    16   128   198]
 [   29  8000 32000 ...     8    32   269]
 [   29  8000 32000 ...     8    32   220]
 ...
 [  125  2000  8000 ...     2    14    52]
 [  480   512  8000 ...     0     0    67]
 [  480  1000  4000 ...     0     0    45]] [ 199  253  253  253  132  290  381  381  749 1238   23   24   70  117
   15   64   23   29   22  124   35   39   40   45   28   21   28   22
   28   27  102  102   74   74  138  136   23   29   44   30   41   74
   74   74   54   41   18   28   36   38   34   19   72   36   30   56
   42   34   34   34   34   34   19   75  113  157   18   20   28   33
   47   54   20   23   25   52   27   50   18   53   23   30   73   20
   25   28   29   32  175   57  181  181   32   82  171  361  350  220
  113   15   21   35   18   20   20   28   45   18   17   26   28   28
   31   31   42   76   76   26   59   65  101  116   18   20   20   30
   44   44   82   82  128   37   46   46   80   88   88   33   46   29
   53   53   41   86   95 

In [ ]:
bankdrop = bank.drop(bank[(bank['pdays'] == -1)].index)
xB = bankdrop.drop(['y', 'job', 'education', 'contact',  'poutcome', 'marital', 'month'], axis = 'columns').replace({'yes': 1, 'no': 0}).to_numpy()
yB = bankdrop['y'].to_numpy()
print(xB, yB)

[[  33    0  882 ...    1  151    3]
 [  42    0 -247 ...    1  166    1]
 [  33    0 3444 ...    1   91    4]
 ...
 [  73    0 2850 ...    1   40    8]
 [  72    0 5715 ...    5  184    3]
 [  37    0 2971 ...    2  188   11]] ['no' 'yes' 'yes' ... 'yes' 'yes' 'no']


4. un modello di classificazione o regressione (a seconda di ciò che è richiesto)

In [ ]:
from sklearn.model_selection import train_test_split

XH_train, XH_test, yH_train, yH_test = train_test_split(xH, yH,
                                                    test_size = 0.33,
                                                    random_state = 123)

XB_train, XB_test, yB_train, yB_test = train_test_split(xB, yB,
                                                    test_size = 0.33,
                                                    random_state = 123)

In [ ]:
XH_train.shape,yH_train.shape,XH_test.shape,yH_test.shape

((140, 7), (140,), (69, 7), (69,))

In [ ]:
XB_train.shape,yB_train.shape,XB_test.shape,yB_test.shape

((5532, 10), (5532,), (2725, 10), (2725,))

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(XB_train, yB_train)
predictB = neigh.predict(XB_test)
print(f'dati predetti dal metodo =                {predictB[:10]}')
print(f'dati reali presenti nel dataset di test = {yB_test[:10]}')

dati predetti dal metodo =                ['no' 'no' 'no' 'no' 'no' 'yes' 'no' 'no' 'no' 'no']
dati reali presenti nel dataset di test = ['yes' 'no' 'no' 'no' 'no' 'yes' 'no' 'no' 'no' 'yes']


In [ ]:
from sklearn.linear_model import LinearRegression
regr = LinearRegression()

regr.fit(XH_train,yH_train)
predictHL = regr.predict(XH_test)

print(f'dati predetti dal metodo = {predictHL[:10].round(decimals=2)}')
print(f'dati reali presenti nel dataset di test = {yH_test[:10]}')

dati predetti dal metodo = [ 41.64  59.4  -11.82  20.6  197.12 239.84 810.04   3.05 460.13 246.44]
dati reali presenti nel dataset di test = [ 67  64  19  46 149 227 919  21 361 102]


In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly2 = PolynomialFeatures(degree = 2)
XH_train_poly2 = poly2.fit_transform(XH_train)

modello = LinearRegression()
modello.fit(XH_train_poly2, yH_train)

XH_test_poly2 = poly2.transform(XH_test)
predictHP2 = modello.predict(XH_test_poly2)

In [ ]:
poly3 = PolynomialFeatures(degree = 3)
XH_train_poly3 = poly3.fit_transform(XH_train)

modello = LinearRegression()
modello.fit(XH_train_poly3, yH_train)

XH_test_poly3 = poly3.transform(XH_test)
predictHP3 = modello.predict(XH_test_poly3)

5. una valutazione del modello con una breve descrizione della sua bontà nell'effettuare previsioni

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(yB_test, predictB))

'''
Il modello funziona abbastanza bene con i risultati negativi, ma con quelli positivi ne sbaglia uno su due, quindi non è buono, è come se indovinasse casualmente.
'''

              precision    recall  f1-score   support

          no       0.84      0.87      0.86      2120
         yes       0.49      0.42      0.46       605

    accuracy                           0.77      2725
   macro avg       0.67      0.65      0.66      2725
weighted avg       0.76      0.77      0.77      2725



'\nIl modello funziona abbastanza bene con i risultati negativi, ma con quelli positivi ne sbaglia uno su due, quindi non è buono, è come se indovinasse casualmente.\n'

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error

# The coefficients
print('Coefficients: \n', regr.coef_)

# The mean squared error
print('Mean squared error: %.2f' %mean_squared_error(yH_test, predictHL))

# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f' %r2_score(yH_test, predictHL))

Coefficients: 
 [0.03486668 0.00512619 0.00270429 0.10464564 1.1255631  0.13473355
 0.63313831]
Mean squared error: 1198.13
Coefficient of determination: 0.93


In [ ]:
# The coefficients
print('Coefficients: \n', regr.coef_)

# The mean squared error
print('Mean squared error: %.2f' %mean_squared_error(yH_test, predictHP2))

# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f' %r2_score(yH_test, predictHP2))

# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f' %r2_score(yH_test, predictHP3))

Coefficients: 
 [0.03486668 0.00512619 0.00270429 0.10464564 1.1255631  0.13473355
 0.63313831]
Mean squared error: 51.01
Coefficient of determination: 1.00
Coefficient of determination: -41.05


In [ ]:
'''
Regressione Lineare: il modello risulta ottimo, con un coefficiente di determinazione di 0.93, quindi molto buono. Evidentemente i dati del dataset sono di qualità.
Regressione Polinomiale: il modello restituisce valori perfetti nel caso in cui il grado della funzione è impostato su 2, visto che il coefficiente di determinazione è pari a 1.
                         Ma appena il grade viene aumentato a 3, avviene un caso di overfitting, e il coefficiente di determinazione diventa negativo, rendendo il modello totalmente inutilizzabile.
'''

'\nRegressione Lineare: il modello risulta ottimo, con un coefficiente di determinazione di 0.93, quindi molto buono. Evidentemente i dati del dataset sono di qualità.\nRegressione Polinomiale: il modello restituisce valori perfetti nel caso in cui il grado della funzione è impostato su 2, visto che il coefficiente di determinazione è pari a 1.\n                         Ma appena il grade viene aumentato a 3, avviene un caso di overfitting, e il coefficiente di determinazione diventa negativo, rendendo il modello totalmente inutilizzabile.\n'